name: Fly Deploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    name: Deploy Fly App
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Select Fly Config
        id: config
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "config=fly.boda-t0amgq.toml" >> $GITHUB_OUTPUT
            echo "Deploying Production → boda-t0amgq"
          else
            echo "config=fly.boda-0mqtrq.toml" >> $GITHUB_OUTPUT
            echo "Deploying Staging → boda-0mqtrq"
          fi

      - name: Deploy to Fly.io
        run: |
          flyctl deploy -c ${{ steps.config.outputs.config }} --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
